apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-account
  namespace: restaurant-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-role
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses/status
    verbs:
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-role
subjects:
  - kind: ServiceAccount
    name: traefik-account
    namespace: restaurant-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: restaurant-app
data:
  traefik.yml: |
    api:
      dashboard: true
      insecure: true
    
    entryPoints:
      web:
        address: ":80"
      dashboard:
        address: ":8082"
    
    providers:
      kubernetesIngress:
        namespaces:
          - restaurant-app
      file:
        directory: /etc/traefik/dynamic
        watch: true
    
    # Access logs configuration
    accessLog: {}
    
    # Log configuration
    log:
      level: INFO
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-dynamic-config
  namespace: restaurant-app
data:
  conf.yml: |
    http:
      middlewares:
        auth-headers:
          headers:
            accessControlAllowMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            accessControlAllowHeaders:
              - "Content-Type"
              - "Authorization"
            accessControlAllowOriginList:
              - "*"
            accessControlMaxAge: 100
            addVaryHeader: true
        
        rate-limit:
          rateLimit:
            average: 100
            burst: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: restaurant-app
spec:
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-account
      containers:
      - name: traefik
        image: traefik:v2.10
        ports:
        - name: web
          containerPort: 80
        - name: dashboard
          containerPort: 8082
        volumeMounts:
        - name: traefik-config
          mountPath: /traefik.yml
          subPath: traefik.yml
        - name: traefik-dynamic-config
          mountPath: /etc/traefik/dynamic
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
      volumes:
      - name: traefik-config
        configMap:
          name: traefik-config
      - name: traefik-dynamic-config
        configMap:
          name: traefik-dynamic-config
---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: restaurant-app
spec:
  selector:
    app: traefik
  ports:
  - name: web
    port: 80
    targetPort: 80
  - name: dashboard
    port: 8082
    targetPort: 8082
  type: LoadBalancer
